
const Sockets = {
    CONNECTION: "connection",
    DISCONNECT: "disconnect",

    //Client To Server
    C2S_CREATE_ROOM: "C2S_CREATE_ROOM",
    C2S_JOIN_ROOM: 'C2S_JOIN_ROOM',
    C2S_ONLY_SIGNAL_ROOM: 'C2S_ONLY_SIGNAL_ROOM',
    C2S_ACCEPT_ROOM: 'C2S_ACCEPT_ROOM',
    C2S_DECLINE_ROOM: 'C2S_DECLINE_ROOM',
    C2S_SEND_DATA_TO_ROOM: 'C2S_SEND_DATA_TO_ROOM',
    C2S_LEAVE_ROOM: 'C2S_LEAVE_ROOM',

    //Server To Client
    S2C_CREATED_ROOM: 'S2C_CREATED_ROOM',
    S2C_JOINED_ROOM: 'S2C_JOINED_ROOM',
    S2C_ONLY_SIGNAL_ROOM: 'S2C_ONLY_SIGNAL_ROOM',
    S2C_ACCEPTED_ROOM: 'S2C_ACCEPTED_ROOM',
    S2C_DECLINED_ROOM: 'S2C_DECLINED_ROOM',
    S2C_LEFT_ROOM: 'S2C_LEFT_ROOM',
    S2C_ENDED_ROOM: 'S2C_ENDED_ROOM',
    S2C_SEND_DATA_TO_ROOM: 'S2C_SEND_DATA_TO_ROOM'
}

module.exports = { Sockets };